# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  enable-experiment:
    - extension-methods
    - non-nullable
  exclude:
    - '**/*.g.dart'
    - 'lib/i10n/*'
  errors:
    flutter_style_todos: ignore
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true