# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  enable-experiment:
    - non-nullable
    - extension-methods
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true