name: wr_app
description: WorldRIZe App
authors:
  - wakame-tech
  - yoshiki301
version: 0.1.0-dev
repository: https://github.com/WorldRIZe/wr-app

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_swiper : ^1.1.5
  getflutter: ^1.0.4
  provider: ^4.0.2
  flappy_search_bar: 1.4.1
  assets_audio_player: ^1.2.3
  story_view: ^0.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
  assets:
    - res/
