# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :staging do
    # add actions here: https://docs.fastlane.tools/actions
    disable_automatic_code_signing(path: "Runner.xcodeproj")

    build_app(
      scheme: "Staging",
      workspace: "Runner.xcworkspace",
      include_bitcode: true
    )

    enable_automatic_code_signing(path: "Runner.xcodeproj")

    puts ENV['FB_TOKEN']

    firebase_app_distribution(
      app: "1:34380133980:ios:795c786ca8bf4735fc1899",
      testers: "kamata1919@gmail.com",
      release_notes: "Release from Fastlane",
      ipa_path: "./build/Runner/Runner.ipa",
      firebase_cli_token: ENV['FB_TOKEN']
    )
  end
end
